--Excluindo o registro caso já exista
IF EXISTS (SELECT 1 FROM PERFIL WHERE NOME = 'USER_ROLE')
BEGIN
    DELETE FROM PERFIL WHERE NOME = 'USER_ROLE'
END

--Excluindo o registro caso já exista
IF EXISTS (SELECT 1 FROM PERFIL WHERE NOME = 'USER_ADMIN')
BEGIN
    DELETE FROM PERFIL WHERE NOME = 'USER_ADMIN'
END

--inserindo
INSERT INTO PERFIL(ID, NOME) VALUES(NEWID(), 'USER_ROLE')
INSERT INTO PERFIL(ID, NOME) VALUES(NEWID(), 'USER_ADMIN')

--consultando
SELECT * FROM PERFIL
